server:
  port: 8888
  servlet:
    context-path: /uaa  

spring:
  application:
    name: authentication-server
  profiles:
    active: local
  
---
spring:
  profiles: local
  cloud:
    kubernetes:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: sa
    password: sa
  jpa:
    generate-ddl: true # switches the feature on/off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        dll-auto: update # initialise db using hibernate
        cache:
          use_second_level_cache: false
          provider_class: org.hibernate.cache.NoCacheProvider
        temp:
          use_jdbc_metadata_defaults: false


security:
  jwtSigner:
    asymmetric: false
    signingKey: ChangeMe
  clients:
  - name: browser
    scopes: ui
  - name: searchService
    clientSecret: SearchService123
    scopes: search

---
spring:
  profiles: kubernetes
  cloud:
    kubernetes:
      reload:
        enabled: true